select * from (select 
	fundataadmissao as database,
	(select id_gerado from public.controle_migracao_registro where hash_chave_dsk = md5(concat('300','vinculo-empregaticio',regcodigo::varchar))) as vinculoEmpregaticio,
	(case fc.regcodigo when 24 then 'true' else 'false' end) as contratoTemporario,
	'NORMAL' as indicativoAdmissao,
	'URBANO' as naturezaAtividade,
	'ADMISSAO' as tipoAdmissao,
	null as primeiroEmprego,
	 (case funtipoemprego when 1 then 'true' else  'false' end) as primeiroEmprego,
	 (case regcodigo when 1 then  'true' else	'false'	 end) as optanteFgts,
	fundataopcaofgts as dataOpcao,
	ifcsequenciafgts as contaFgts,
	unicodigocsi as sindicato,
	null as tipoProvimento,
	null as leiContrato,
	txjcodigo as atoContrato,
	fundatanomeacao as dataNomeacao,
	fundataposse as dataPosse,
	null as tempoAposentadoria,
	null as previdenciaFederal,
	null as previdencias,
	carcodigo as cargo,
	null as cargoAlterado,
	txjcodigo as atoAlteracaoCargo,
	null as areaAtuacao,
	null as areaAtuacaoAlterada,
	null as motivoAlteracaoAreaAtuacao,
	funocupavaga as ocupaVaga,
	null as salarioAlterado,
	null as origemSalario,
	nivcodigo as nivelSalarial,
	null as classeReferencia,
	null as cargoComissionado,
	null as areaAtuacaoComissionado,
	false as ocupaVagaComissionado,
	null as salarioComissionado,
	null as nivelSalarialComissionado,
	null as classeReferenciaComissionado,
	'MENSALISTA' as unidadePagamento,
	(case funformapagamento when 2 then 'CREDITO_EM_CONTA'  when 3 then 'DINHEIRO' when 4 then 'CHEQUE' else 'DINHEIRO' end) as formaPagamento,
	ifcsequenciapaga as contaBancariaPagamento,
	(select id_gerado from public.controle_migracao_registro where hash_chave_dsk = md5(concat('300', 'configuracao-ferias', 1))) as configuracaoFerias,
	cast(regexp_replace(funhorastrabmes, '\:\d{2}$', '', 'gi') as integer) as quantidadeHorasMes,
	(cast(regexp_replace(funhorastrabmes, '\:\d{2}$', '', 'gi') as integer)/5) as quantidadeHorasSemana,
	false as jornadaParcial,
	null as dataAgendamentoRescisao,
	null as funcoesGratificadas,
	null as dataTerminoContratoTemporario,
	null as motivoContratoTemporario,
	null as tipoInclusaoContratoTemporario,
	null as dataProrrogacaoContratoTemporario,
	funcartaoponto as numeroCartaoPonto,
	null as parametroPonto,
	null as indicativoProvimento,
	null as orgaoOrigem,
	null as matriculaEmpresaOrigem,
	null as dataAdmissaoOrigem,
	(case fc.funnocivos   when 0 then null   when 1 then 'NUNCA_EXPOSTO_AGENTES_NOCIVOS'  when 2 then 'EXPOSTO_APOSENTADORIA_15_ANOS'  when 5 then 'EXPOSTO_APOSENTADORIA_15_ANOS'     when 3 then 'EXPOSTO_APOSENTADORIA_20_ANOS'  when 7 then 'EXPOSTO_APOSENTADORIA_20_ANOS'   when 4 then 'EXPOSTO_APOSENTADORIA_25_ANOS'    when 8 then 'EXPOSTO_APOSENTADORIA_25_ANOS'    else     null    end) as ocorrenciaSefip,
	null as controleJornada,
	null as configuracaoLicencaPremio,
	null as configuracaoAdicional,
	null as processaAverbacao,
	null as dataFinal,
	null as dataProrrogacao,
	null as instituicaoEnsino,
	null as agenteIntegracao,
	null as formacao,
	null as formacaoPeriodo,
	null as formacaoFase,
	null as estagioObrigatorio,
	null as objetivo,
	null as numeroContrato,
	null as possuiSeguroVida,
	null as numeroApoliceSeguroVida,
	null as categoriaTrabalhador,
	null as responsaveis,
	null as dataCessacaoAposentadoria,
	null as entidadeOrigem,
	null as motivoAposentadoria,
	null as funcionarioOrigem,
	null as tipoMovimentacao,
	null as motivoInicioBeneficio,
	null as duracaoBeneficio,
	null as dataCessacaoBeneficio,
	null as motivoCessacaoBeneficio,
	null as matriculaOrigem,
	null as responsavel,
	null as dataInicioContrato,
	(CASE fc.funsituacao WHEN  1 THEN 'TRABALHANDO'  WHEN 2 THEN 'AFASTADO' ELSE 'DEMITIDO' end) as situacao,
	null as inicioVigencia,
	'FUNCIONARIO' as tipo,
	(select id_gerado from public.controle_migracao_registro where hash_chave_dsk = md5(concat('300', 'pessoa-fisica', (select regexp_replace(u.unicpfcnpj,'[/.-]','','g') from  wun.tbunico u where u.unicodigo  = fc.unicodigo))))  as pessoa,
	fc.fcncodigo as codigoMatricula,
	null as eSocial,
	null as grupoFuncional,
	null as jornadaTrabalho,
	funsalariobase as rendimentoMensal,
	txjcodigo as atoAlteracaoSalario,
	null as motivoAlteracaoSalario,
	null as validationStatus,
	cnccodigo as organograma,
	null as lotacoesFisicas,
	null as historicos
from wfp.tbfuncontrato as fc  join wfp.tbfuncionario as f on f.fcncodigo = fc.fcncodigo and f.odomesano = fc.odomesano
where fc.odomesano = 202009) as s
where (select id_gerado from public.controle_migracao_registro where hash_chave_dsk = md5(concat('300', 'matricula', codigoMatricula, numeroContrato))) is null
limit 10


